CREATE TABLE IF NOT EXISTS "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar,
  "login" varchar,
  "name" varchar,
  "birthday" date
);

CREATE TABLE IF NOT EXISTS "friends" (
  "user_id" integer REFERENCES "users" ("id"),
  "friend_id" integer REFERENCES "users" ("id"),
  "request_status" bool,
  "created_at" timestamp,
   PRIMARY KEY ("user_id", "friend_id")
);


CREATE TABLE IF NOT EXISTS "ratings" (
  "id" integer PRIMARY KEY,
  "rating_title" varchar
);

CREATE TABLE IF NOT EXISTS "films" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "description" text,
  "release_date" date,
  "duration" integer,
  "rating_id" integer REFERENCES "ratings" ("id")
);

CREATE TABLE IF NOT EXISTS "likes" (
  "film_id" integer REFERENCES "films" ("id"),
  "user_id" integer REFERENCES "users" ("id"),
  "created_at" timestamp,
   PRIMARY KEY ("film_id", "user_id")
);

CREATE TABLE IF NOT EXISTS "genres" (
  "id" integer PRIMARY KEY,
  "name" varchar
);

CREATE TABLE IF NOT EXISTS "film_genres" (
  "film_id" integer REFERENCES "films" ("id"),
  "genre_id" integer REFERENCES "genres" ("id")
);
